export { ReactComponent as AppleIcon } from './apple.svg';
export { ReactComponent as AppleIconRound } from './apple-round.svg';
export { ReactComponent as AstroAvatar } from './astro.svg';
export { ReactComponent as AstroLogin } from './astro-login.svg';
export { ReactComponent as FacebookIcon } from './facebook.svg';
export { ReactComponent as FacebookIconRound } from './facebook-round.svg';
export { ReactComponent as EmailIcon } from './email.svg';
export { ReactComponent as EmailIconRound } from './email-round.svg';
export { ReactComponent as GoogleIcon } from './google.svg';
export { ReactComponent as GoogleIconRound } from './google-round.svg';
export { ReactComponent as LinkedInIcon } from './linkedin.svg';
export { ReactComponent as LinkedInIconRound } from './linkedin-round.svg';
export { ReactComponent as SalesforceLogo } from './salesforce.svg';
export { ReactComponent as SalesforceIcon } from './salesforce-icon.svg';
export { ReactComponent as SalesforceIconRound } from './salesforce-round.svg';
export { ReactComponent as TrailblazerLogo } from './trailblazer-me.svg';
export { ReactComponent as TrailblazerMe } from './_tbme.svg';

export * from './arid-dunes';
export * from './astro';
